main: add missing header for stat flags
main.c:438:57: error: use of undeclared identifier 'S_IRUSR'
        int fd = shm_open(shm_name, O_RDWR | O_CREAT | O_EXCL, S_IRUSR | S_IWUSR);
                                                               ^
main.c:438:67: error: use of undeclared identifier 'S_IWUSR'
        int fd = shm_open(shm_name, O_RDWR | O_CREAT | O_EXCL, S_IRUSR | S_IWUSR);
                                                                         ^